services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos_api
    restart: always
    env_file:
      - .env.docker
    volumes:
      - uploads_data:/app/uploads
    networks:
      - traefik

    labels:
      - "traefik.enable=true"

      # 🔥 DOMAIN (CHANGE ONLY THIS WHEN NEEDED)
      - "traefik.http.routers.pos.rule=Host(`${API_DOMAIN}`)"

      - "traefik.http.routers.pos.entrypoints=websecure"
      - "traefik.http.routers.pos.tls.certresolver=le"

      # backend port inside container
      - "traefik.http.services.pos.loadbalancer.server.port=5000"

volumes:
  uploads_data:

networks:
  traefik:
    external: true